### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [Timen/squeezenext-tensorflow#1]
Please upload the results for ImageNet, TINYImageNet, CIFAR-10

**Comment by Timen** [comment]
I am currently not planning to generate results for these datasets, maybe try contacting the authors of the original paper at the official repo:
https://github.com/amirgholami/SqueezeNext

**Comment by Jayan-K-Duggal** [comment]
Can you help me understand, how to load pytorch checkpoint model of squeezenext to test on new images

**Comment by Timen** [comment]
I'm sorry but I have no experience working with pytorch, you will have to figure that out yourself.
