### ISSUE TITLE
Is there any tf.keras implmentation for squeezenext network? 

### ISSUE THREAD

**Issue by was84san** [Timen/squeezenext-tensorflow#2]
Hi, 
I just wonder if there is any tf.keras implementation for the squuezenext, I tried to convert the tensorflow implementation one, but it was hard. Can you provide the tf.keras implementation?

**Comment by Timen** [comment]
I am not planning to implement a tf.keras version, you can try asking the authors of the paper at the official repo:
https://github.com/amirgholami/SqueezeNext
